### PR TITLE
Support Python 3.6 only

### PR DESCRIPTION
**Pull request by lfdebrux**
Add python_requires specification to setup.py that explicitly declares which versions of Python this library supports/is tested on.

Part of https://trello.com/c/wWFsv1SU/230-be-clear-in-our-libraries-what-versions-of-python-we-support

### CODE REVIEW

**Comment by risicle** [comment]
Travis is sad :cry:

**Comment by katstevens** [comment]
Was Travis running tests with a different Python version before now?

**Comment by risicle** [comment]
Fails for me in a similar way.

**Comment by risicle** [comment]
*Though* I note that it's doing this with me on master too :/

**Comment by risicle** [comment]
@katstevens have you tried wiping out your venv and trying again?

**Comment by risicle** [comment]
If I may be so bold, sir?

**Comment by lfdebrux** [comment]
Travis is happy now

**Comment by lfdebrux** [comment]
Trying out a Python version badge

screenshot from 2018-11-26 16-35-46

**Pull request merged**
